### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by jonnepaa** [jonnepaa/wireless_project#11]
## Introduction

We can put all of the important information relating to the presentation in this thread. Discussion and questions can happen in the Facebook group chat.

The presentation is on the deployment of a wireless network for an educational environment. See below for a physical overview of the campus

## Campus overview

The campus consists of four identical buildings and an outdoor area in the middle.

![grounds2](https://cloud.githubusercontent.com/assets/14025386/15699687/24cb7578-2812-11e6-9ff9-e0f0f05c16a9.png)

_Building A has a server room on the side, wireless will not be deployed there._

Each building has 3 identical floors. Here is the floor map.

![](http://i.imgur.com/7khfUXI.png)

## Presentation breakdown

We'll split up the focus areas as follows:

Person | Topic
--- | ---
Johannes | Introduction
Andreas | High density of users
 | Expect lots of access points (numerous rooms)
Jack | Two-dimensional trap (Multi floors) - This is related to Andreas' topics so follow on from that.
Johannes | Outdoor coverage
Wendy | Students can be curious and destructive
 | Location services
Jack | Multi-venders of WLAN equipment

\* _This is also the order we will present in._

---

Everybody should add a comment to this thread for each section they are presenting. Put an overview of what you will present, and attach your slides.

If you want to edit the floor-plan to use in a slide or something, load [this file](https://github.com/jonnepaa/wireless_project/files/287603/wireless_deployment.zip) into http://draw.io

Also, learn as much as possible about deploying wireless in general, not just your parts. Then we can handle any questions they throw at us.

Good luck.

**Comment by jonnepaa** [comment]
@differentuser - Please confirm that you've seen this.

@awwan @JackSch @differentuser - Make sure you are subscribed to this thread. There's a button to the right under __notifications__.

We can discuss the presentation here, and by being subscribed we'll get email alerts.

@awwan - Since it is most related to your parts, could you include an AP locations topology in your slides and talk about that a bit?

**Comment by awwan** [comment]
I found this reference applicable, any thoughts/suggestions?

@jonnepaa - I am uncertain of how/where to put APs. Do you have any suggestion?
From my research atm, or similar to our lecture room why got several APs in a room is to: loadbalancing, device locating, and rogue detection.. Should it be fine if I copy Aruba design? Or just minimizing AP deployment, just need a decision on this.

[youtube watch?v=-lbcQFpTUQs](https://www.youtube.com/watch?v=-lbcQFpTUQs)
>### Large Enterprise Wireless Deployment, Strategies and Perspectives - YouTube
>
> **Channel Allocation**
> Channel Striping - alternate channels set on each floor of a building
> Channel Layering - Multiple channels in single area
> 
> **Large Classrooms/Lecture Halls**
> Eg.250+seats with 250 seats
> >APs required @ 2 devices per person:
> 		250seats * 2 devices / 80 devices per radio / 2 radios per AP
> 		= 3 APs
>
> >	Bandwidth:
>
> >      a. Highest Assumption HD video @ 6 Mbps + email @ 0.5 Mbps
> 		250x ( 6+ 0.5 Mbps) = 1,625 Mbps
> 		@ 50 Mbps per channel, ~33 Channels or 17 APs
> 
>  >      b. Practical Assumption SD video @ 1 Mbps + email @ 0.5 Mbps
> 		250x ( 1+ 0.5 Mpbs) = 375 Mbps
>       7.5 channels or 4 APs
>
> Deployed:	6 APs	6 Channel pairs

**Comment by jonnepaa** [comment]
That seems like decent info. 

Maybe choose an AP model we can deploy. We can say it's a brand new deployment so we are getting lots of brand new ones of the same type.

Then work out how many clients each can support, like they've done above, and figure out how many people will be in those classrooms/areas at the same time. That will tell us how many APs to deploy.

As for channel allocation, it sounds like a mix of striping and layering would be good. For example floor one could be set up like this:
![level1](https://cloud.githubusercontent.com/assets/14025386/15637684/27e46808-265c-11e6-8151-f4d96b19b5fb.png)

And floor 2 could be like this:
![level2](https://cloud.githubusercontent.com/assets/14025386/15637713/377e8802-265c-11e6-947f-25e70ea4ace2.png)

That way APs next to each other do not interfere with each other, and APs directly above or below each other do not interfere.

Remember there are 3 non-overlapping channels; 1, 6 and 11. Try and make the set up so APs next to or above another one are on different ones of those channels.

**Comment by jonnepaa** [comment]
@awwan Do you have Wendy's email or something? I'm not sure he has seen this.

**Comment by awwan** [comment]
@jonnepaa my last communication with him was from facebook, https://www.facebook.com/wendy.schwarzanazegger

**Comment by jonnepaa** [comment]
@awwan When you talk about the channel assignments for the APs, remember that the APs will have multiple radios, so we can do 2.4Ghz and 5Ghz from each AP. We will need a 2.4Ghz channel and a 5Ghz channel for each AP that doesn't overlap with the neighbours.

Have you thought of an AP to deploy? If you haven't we can just say the [Cisco Aironet 1850](http://www.cisco.com/c/en/us/products/wireless/aironet-1850-series-access-points/index.html) for indoor use and the [Cisco Aironet 1530](http://www.cisco.com/c/en/us/products/collateral/wireless/aironet-1530-series/data_sheet_c78-728356.html) for outdoor use.

On the topic of hardware, we need some WLCs, I think we could just use 2 [Cisco 8540 WLCs](http://www.cisco.com/c/en/us/products/wireless/8540-wireless-controller/index.html).
They handle 40Gb/s of throughput so they should be fine.

Oh and also, let's scale the deployment up to 4 buildings, each will be identical, see the next comment.

**Comment by awwan** [comment]
Hi guys,

Was about to post this before you mentioned above.. oh right forgotten about WLCs.
Btw when is our turn tomorrow?

My map atm:

3 APs WiFi per floor

> 1 AP is 3x3 MIMO 2.4Ghz + 5Ghz
> 2.4Ghz x 3 Channels: 1 6 11
> 5Ghz x 3 Channels: any
> Reference: [Unifi AP AC](https://www.ubnt.com/unifi/unifi-ap-ac-pro/)

Color:
Soft: 2.4+5Ghz supported
Yellow: 5Ghz Limited
Red: All low reception

Should be the same with other 3 floors, except the outside area, should put any around the building?

High density solution: load balancing
The idea: the closest to WiFi will be supported by 5Ghz, otherwise 2.4Ghz
If device not getting reception -> tough luck, everyone is upgrading devices at least one in 2 years.
Should be getting up to dated technology.

[wireless_site2.zip](https://github.com/jonnepaa/wireless_project/files/292521/wireless_site2.zip)
![wireless_site2](https://cloud.githubusercontent.com/assets/15132460/15696163/4f2b00fc-27f1-11e6-808c-6790ddcfb2b0.png)

Should I put them in slides?
I am at work atm, although I am trying my best to prioritise this.
Wish for your understanding.

Cheers,
Andreas.

**Comment by jonnepaa** [comment]
@awwan You don't need to worry too much about WLCs. More about where APs go and how many.
That is a good start, but I'm not sure 3 APs are enough per floor. If we imagine there will be 30 people in each classroom, plus more hanging out in the reception area and corridors.

With the current setup, that might be 60 people per AP. I'm not sure what the figures are for devices supporting 5Ghz, but let's say 40 can use the 5Ghz radio and the other 20 use 2.4Ghz.

If we use the Aironet 1850, the 5Ghz radio can do up to 1733Mb/s while the 2.4Ghz can only do 214Mb/s. 

That's still theoretically usable bandwidth per person, but I'm sure all the collisions from having so many on the same WLAN will significantly lower the throughput. Maybe find some data on this?

There's also the problem of walls and obstacles, classrooms will get pretty bad signals if the APs are in the corridor.

I'd suggest doubling the number of APs, having one in each classroom, one for the reception area and one in the corridor, the transmit power can be lowered on each to cover a smaller area so less clients use each AP.

If you can make some simple calculations to go with this, especially how having lots of clients reduces throughput and maybe the effect of walls and such, I think Khaled and David would like that.

Remember, each AP (Aironet 1850) has an uplink of 1Gb/s and 2 radios at a max of 1.7Gb/s and 214Mb/s.

Having a heat-map thing like you done is a good idea.

**Comment by awwan** [comment]
What I found for 2.4Ghz is 1 channel (without/with interference combined)
can only handle 70MB/s max ,
Therefore 3 channels in an area is approx 210Mb/s,

Having too much AP in an area will collides so much especially with 2.4Ghz, and 5Ghz is concerned with distance.

Imagining each floor could collides each other,
so it's suggested there are variations of channels for each floor.

5Ghz is very high without colision/problem I suppose, just the problem is distance and obstructions/sight.

I thought 1 AP could support around 100 devices, but yeah I haven't really looked up for specific devices, I am looking for cisco atm.

I assume for antenna we will use omnidirectional? As assuming all devices will not have as good as AP antenna reception?

**Comment by jonnepaa** [comment]
## Updated deployment

As I said, we'll scale up the deployment to four buildings. Each will be identical so it doesn't change much, just makes the deployment sound more realistic.

Here is how the buildings are situated relative to each other.

![grounds](https://cloud.githubusercontent.com/assets/14025386/15697387/ef43c442-27fc-11e6-85c6-5492d0b04c6d.png)

I will do an overview of the infrastructure in the introduction, covering WLCs and the core and distribution network layers connecting the APs to the WLCs. I'll also briefly mention the hardware we will use.

I'll upload a network topology of the core and distribution layers soon.

Also the traffic we want our wireless deployment to support is:
```
100 people per floor @ 10Mb/s = 1Gb/s per floor. 
3Gb/s per building.
12Gb/s for entire campus.
```
\* _I think I'll downgrade the WLCs, 2x40Gb/s is kind of excessive._

This is pretty easy to handle, the biggest problem is wireless collisions. __We definitely need some stats on wireless collisions.__

**Comment by jonnepaa** [comment]
@awwan, I edited that comment a bit.

To avoid collisions we can use low transmit powers to cover a smaller area.

We also use striping and layering so neighbouring APs are using different channels. They won't interfere with each other.

Also, each AP would only use 2 channels right? One on 2.5Ghz and one on 5Ghz.
MIMO just means there are multiple antennas per radio, so they get better reception,
__Each AP still only has 2 radios, so 2 channels; One on 2.5Ghz and one on 5Ghz.__

**Comment by jonnepaa** [comment]
## Hardware

These are the devices we will deploy:

__Wireless Controllers__: [Cisco 5520 Wireless Controller](http://www.cisco.com/c/en/us/products/collateral/wireless/5520-wireless-controller/datasheet-c78-734257.html)

These can do 20Gb/s of throughput each, so two of these as a fail-over pair is more than enough.

__Indoor APs__: [Cisco Aironet 1850](http://www.cisco.com/c/en/us/products/collateral/wireless/aironet-1850-series-access-points/datasheet-c78-734256.html)

We'll need something like 80 of these. Depending on Andreas' layout.

__Outdoor APs__: [Cisco Aironet 1520](http://www.cisco.com/c/en/us/products/collateral/wireless/aironet-1530-series/data_sheet_c78-728356.html)

We'll need around 9 of these. Depending on my layout.

**Comment by awwan** [comment]
@jonnepaa I am understanding that 802.11n MIMO is like having 2 2.4Ghz channels like raspberry pi usb wifi, but please correct me if I am wrong, I am totally struck with these technical stuff.

Will be this good enough like approx 6-7 APs in a floor
![wireless_aps](https://cloud.githubusercontent.com/assets/15132460/15698167/f8969af8-2804-11e6-8621-856872a42aa8.png)

So, my assumptions for indoor APs:
1 AP : a 2.4Ghz + a 5Ghz channels each, ( E.g AP1 Channel 1 & 36 )
1 AP, Max capacity 200 + 200 = 400 devices

**Comment by jonnepaa** [comment]
## Introduction Section

_Here's an overview of what I'll present in this section_

1. Explain the environment we are deploying wireless in:
  + Show floor plan of buildings.
  + Show map of campus.
2. Give an overview of the wireless data needs, eg how many people and how much bandwidth each.
3. Show the hardware we will deploy (just briefly).
4. Show the backing infrastructure, so core and distribution networks, where WLCs and APs fit into the topology.

**Comment by jonnepaa** [comment]
## Network Topology

Here is the network topology of the campus. It includes the core and distribution layers, and parts of the access layer.

__Core layer__: is the two switches in the centre (highlighted red).

__Distribution layer__: are the layer 3 switches in each building (highlighted blue).

__Access layer__: are the layer 2 switches in the buildings.

Two access layer switches are shown here for each floor, there are more per floor, but they aren't shown. Access points will be spread across these access layer switches, so if one switch goes down all the APs don't go offline (APs can only be connected to one network, so it's the only redundancy we can give them).

The WLCs are in the server room, they are connected via redundant 20Gb/s links.

![topology1](https://cloud.githubusercontent.com/assets/14025386/15701916/7498db46-2820-11e6-8db4-1967cb4f94d2.png)


\* _Note: The core layer is also housed in the server room._
