### ISSUE TITLE
Add config for BR1_SW1

### ISSUE THREAD

**Issue by jonnepaa** [jonnepaa/wireless_project#4]
+ Shutdown all unused ports
+ Host name
+ Virtual Interface
+ SSH (and local user)
+ Anything else?

**Comment by awwan** [comment]
BR1_SW1 is just a L2 switch?
Just caught my eyes, it might need router-on-a-stick dot1q for vlans purposes.

<img src="https://cloud.githubusercontent.com/assets/15132460/14141296/f06c3cc8-f6c9-11e5-89b9-4cf659e04261.png" width="150">

**Comment by jonnepaa** [comment]
There are no vlans there, just the 172.16.198.0/24 network. It'll work fine with standard routing/switching.

**Comment by awwan** [comment]
[BR1_SW1 link](https://github.com/jonnepaa/wireless_project/commit/4694c0dfb19ecccf25936bf722a4e0f3daca2633)

done.
