### ISSUE TITLE
Configure OSPF

### ISSUE THREAD

**Issue by jonnepaa** [jonnepaa/wireless_project#6]
HQ_SW1 can use RID `1.1.1.1`
HQ_ROUTER can use RID `2.2.2.2`
BR1_ROUTER can use RID `3.3.3.3`

Advertise all Vlans from HQ_SW1
Advertise 172.16.198.0/24 and 172.16.196.0/30 from BR1_ROUTER
Advertise 172.16.196.0/30 and 172.16.199.0/24 from HQ_ROUTER

**Comment by jonnepaa** [comment]
And make appropriate interfaces passive.

**Comment by awwan** [comment]
* HQ_ROUTER can use RID 2.2.2.2
* BR1_ROUTER can use RID 3.3.3.3
* Advertise 172.16.198.0/24 and 172.16.196.0/30 from BR1_ROUTER
* Advertise 172.16.196.0/30 & 172.16.0.4/30 from HQ_ROUTER

> int G0/0 , S0/0/0
 ip ospf message-digest-key 1 md5 landownunder

>router ospf 1
 area 0 authentication message-digest
