### ISSUE TITLE
Design Stage 2 requirements

### ISSUE THREAD

**Issue by jonnepaa** [jonnepaa/wireless_project#7]
What should we do in stage 2?

Add your thoughts here.

@awwan 
@JackSch

**Comment by JackSch** [comment]
Maybe work towards the final goal of all APs being accessable and configured. Keep it simple.

Then add the second WLC.
Clean up any config issues and make sure that it's all working rock solid.

Then maybe stage 3, can be adding all of the things for extra marks. Security and such.

What do you guys think?

**Comment by awwan** [comment]
I second with Jack.
For myself after done stage 2, I would test additional VPN IPSec in between routers.

Happy Easter and have a good one.
See you guys soon.
