### ISSUE TITLE
VM ESXi to HQ_SW1

### ISSUE THREAD

**Issue by awwan** [jonnepaa/wireless_project#9]
Khaled's solution:
```
int f0/9
no switchport trunk allowed vlan 100,190-192,199

int f0/11
switchport access vlan 100
```
My approach on PC:
manually setup IP 10.100.0.231 255.255.255.0
then, able to ping _10.100.0.1_ & _10.100.0.101_

Issues:

- dhcp from 10.100.0.0 not working
- new VMware vSphere Client is needed to access ESXi (_VMware-viclient-all-6.0.0-3016447_ from Khaled)

Attention @jonnepaa @JackSch

**Comment by jonnepaa** [comment]
Ok, the current HQ_SW1 config doesn't have the `trunk allowed vlan...` stuff, so that's fine.
Let's put fa0/20 on VLAN 100 temporarily, fa0/11 is one of our management ports.

Did the SVI on vlan 100 not receive an address from DHCP?

**Comment by awwan** [comment]
yes it didn't receive DHCP from 10.100.0.0, even when I entered `ip helper-address 10.100.0.1` on SVI... the DHCP server could be somewhere .1-101 (_haven't tried_)

also, the same with access port, but when u configured the IP manually, it will be able to ping 10.100.0.0 network.

**Comment by awwan** [comment]
Sorry guys, just to let you know I will not be here this Thursday.
Let me know if there is anything I could help,
Thanks.

**Comment by jonnepaa** [comment]
If you want, just do some reading for the presentation.
(We're doing deployment in an educational environment.)

**Comment by jonnepaa** [comment]
@awwan I lost your email address, what was it?
